// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SalaryService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace OBSalaries.SalaryService {
  /// <summary>
  ///-------------------------------------------
  /// Services for Salaries
  ///-------------------------------------------
  /// </summary>
  public static partial class SalaryService
  {
    static readonly string __ServiceName = "OBSalaries.SalaryService";

    static readonly grpc::Marshaller<global::OBSalaries.SalaryService.SalarySlipRequest> __Marshaller_OBSalaries_SalarySlipRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::OBSalaries.SalaryService.SalarySlipRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::OBSalaries.SalaryService.SalarySlipResponse> __Marshaller_OBSalaries_SalarySlipResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::OBSalaries.SalaryService.SalarySlipResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::OBSalaries.SalaryService.SalarySlipRequest, global::OBSalaries.SalaryService.SalarySlipResponse> __Method_ProcessSalary = new grpc::Method<global::OBSalaries.SalaryService.SalarySlipRequest, global::OBSalaries.SalaryService.SalarySlipResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "ProcessSalary",
        __Marshaller_OBSalaries_SalarySlipRequest,
        __Marshaller_OBSalaries_SalarySlipResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::OBSalaries.SalaryService.SalaryServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SalaryService</summary>
    public abstract partial class SalaryServiceBase
    {
      public virtual global::System.Threading.Tasks.Task ProcessSalary(grpc::IAsyncStreamReader<global::OBSalaries.SalaryService.SalarySlipRequest> requestStream, grpc::IServerStreamWriter<global::OBSalaries.SalaryService.SalarySlipResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SalaryService</summary>
    public partial class SalaryServiceClient : grpc::ClientBase<SalaryServiceClient>
    {
      /// <summary>Creates a new client for SalaryService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SalaryServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SalaryService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SalaryServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SalaryServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SalaryServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::OBSalaries.SalaryService.SalarySlipRequest, global::OBSalaries.SalaryService.SalarySlipResponse> ProcessSalary(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ProcessSalary(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::OBSalaries.SalaryService.SalarySlipRequest, global::OBSalaries.SalaryService.SalarySlipResponse> ProcessSalary(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_ProcessSalary, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SalaryServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SalaryServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SalaryServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ProcessSalary, serviceImpl.ProcessSalary).Build();
    }

  }
}
#endregion
